### ISSUE TITLE
Supporting Subassemblies as Parts?

### ISSUE THREAD

**Issue by shederman** [severedsolo/ScrapYard#1]
Posted here by recommendation from magico13 (https://github.com/magico13/ScrapYard/issues/3#event-1956906977).

Would there be a possible way to have subassemblies stored as parts in the inventory together? I'm thinking a gameplay where we recondition an entire rocket or stage rather than the individual parts that make it up?

You'd have to be able to:

* Identify all parts as coming from a common subassembly
* Put the parts in ScrapYard as one "Part"
* Allow "Break up for parts" for such Subassembly parts
* Possibly also allow a "Build subassembly from parts", if I want to add my Centaur Upper Stage but I want to do it efficiently.

**Comment by severedsolo** [comment]
Issue cleanup. ScrapYard now maintained by @zer0Kerbal
