### ISSUE TITLE
Possibly broke KCT compatibility with KRASHWrapper

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/ScrapYard#3]
See https://forum.kerbalspaceprogram.com/index.php?/topic/160854-16x-oh-scrap-a-scrapyard-based-part-failure-and-reliability-mod-1611-02042019/&do=findComment&comment=3586090

**Comment by ussdefiant60** [comment]
apologies for the delay, Easter took me away from my PC. Sample log attached, didn't go and actually launch any rockets though.
[KSP.log](https://github.com/severedsolo/ScrapYard/files/3104931/KSP.log)

**Comment by Nistenf** [comment]
Hello, I'm also experiencing this bug where part generations don't go up even when they've been built multiple times. I'm using KSP 1.6.1, ScrapYard 1.1.2, OhScrap! 16.1.1, and KRASH 0.5.29.8. Here's the log:
[KSP.log](https://github.com/severedsolo/ScrapYard/files/3109858/KSP.log)

**Comment by severedsolo** [comment]
Thank you - I know I promised to get this done by Wednesday, but it's been a busy week. For now I recommend going back to ScrapYard 1.1.1

**Comment by Beetlecat** [comment]
Once the new expansion hits, I'll more likely than not be hitting KSP again for a while :) Is this still on your (intend)to-do pile?

**Comment by severedsolo** [comment]
Yes, this is the thing I want fixed up before I hand SY over

**Comment by severedsolo** [comment]
Fixed
